services:
  psutarchive-dev-directus:
    container_name: psutarchive-dev-directus
    build: .
    command: >
      sh -c "node cli.js bootstrap --skipAdminInit
      && pm2-runtime start ecosystem.config.cjs"
    ports:
      - 8055:8055
    volumes:
      - .env:/directus/.env
      - ./schema-sync:/directus/schema-sync
    networks:
      - psutarchive-dev-network

  psutarchive-dev-db:
    container_name: psutarchive-dev-db
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - psutarchive-dev-network

networks:
  psutarchive-dev-network:
