services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:17.2-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "--host=localhost", "--username=directus" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_interval: 5s
      start_period: 2s
    network_mode: host
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
  directus:
    build: .
    network_mode: host
    depends_on:
      postgres-dev:
        condition: service_healthy
    volumes:
      - ./configs:/configs
      - ./translations:/translations
    environment:
      SECRET: "a-secret-here"
      DB_CLIENT: "pg"
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_DATABASE: "sampledb"
      DB_USER: "admin"
      DB_PASSWORD: "pass123"
      ADMIN_EMAIL: "admin@email.com"
      ADMIN_PASSWORD: "123"
      SETTINGS_FILE_PATH: /configs/settings.yaml