name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            Thank you for taking the time to open an issue!
            The issue is being triaged. We'll review it and get back to you.

            If you're interested in resolving it yourself, be sure tell us below, and read [CONTRIBUTION.md](https://github.com/Marje3PSUT/.github/blob/main/CONTRIBUTION.md).
            @maintainers

          pullRequestOpened: |
            Please undraft your PR and assign to `@maintainers` when you're done working, and you've verified your work against the [DoD (Definition of Done)](https://github.com/Marje3PSUT/.github/blob/main/DoD.md) document.